[versions]
compose = "1.6.11"
compose-compiler = "1.5.8"
compose-plugin = "1.10.0-alpha02"
junit = "4.13.2"
kotlin = "2.2.20"
apksig = "8.11.1"
tools = "31.11.1"
slf4j = "2.0.17"
buildconfig = "5.6.7"
commons-codec = "1.19.0"
asm = "9.9"
jna = "5.18.1"
logging = "7.0.13"
lifecycle = "2.9.4"
coroutines = "1.10.2"
filekit = "0.12.0"
multiplatform-settings = "1.3.0"
kotlinx-serialization-json = "1.9.0"
kotlinx-datetime = "0.7.1"
about-libraries = "13.0.0"
hot-reload = "1.0.0-rc02"
foojay = "1.0.0"
coil = "3.3.0"
zoomimage = "1.4.0"
apktool = "2.12.1"
ktor = "3.3.1"
richeditor = "1.0.0-rc13"
logback = "1.5.19"
compottie="2.0.1"

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "compose" }
compose-material-icons-extended-desktop = { module = "androidx.compose.material:material-icons-extended-desktop", version.ref = "compose" }
# https://mvnrepository.com/artifact/org.jetbrains.androidx.lifecycle/lifecycle-viewmodel-compose
lifecycle-viewmodel-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
# https://mvnrepository.com/artifact/com.android.tools.build/apksig
android-apksig = { module = "com.android.tools.build:apksig", version.ref = "apksig" }
# https://mvnrepository.com/artifact/com.android.tools/sdk-common
android-sdk-common = { module = "com.android.tools:sdk-common", version.ref = "tools" }
# https://mvnrepository.com/artifact/com.android.tools.apkparser/binary-resources
android-binary-resources = { module = "com.android.tools.apkparser:binary-resources", version.ref = "tools" }
# https://mvnrepository.com/artifact/org.slf4j/slf4j-api
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }
# https://mvnrepository.com/artifact/commons-codec/commons-codec
commons-codec = { module = "commons-codec:commons-codec", version.ref = "commons-codec" }
# https://mvnrepository.com/artifact/org.ow2.asm/asm
asm = { module = "org.ow2.asm:asm", version.ref = "asm" }
# https://mvnrepository.com/artifact/net.java.dev.jna/jna
jna = { module = "net.java.dev.jna:jna", version.ref = "jna" }
# https://github.com/oshai/kotlin-logging
logging = { module = "io.github.oshai:kotlin-logging-jvm", version.ref = "logging" }
# https://github.com/qos-ch/logback
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback"}
# https://github.com/Kotlin/kotlinx.coroutines
kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "coroutines" }
# https://github.com/vinceglb/FileKit
filekit-core = { module = "io.github.vinceglb:filekit-core", version.ref = "filekit" }
filekit-dialogs = { module = "io.github.vinceglb:filekit-dialogs", version.ref = "filekit" }
filekit-dialogs-compose = { module = "io.github.vinceglb:filekit-dialogs-compose", version.ref = "filekit" }
# https://github.com/russhwolf/multiplatform-settings
multiplatform-settings = { module = "com.russhwolf:multiplatform-settings", version.ref = "multiplatform-settings" }
multiplatform-settings-coroutines = { module = "com.russhwolf:multiplatform-settings-coroutines", version.ref = "multiplatform-settings" }
multiplatform-settings-serialization = { module = "com.russhwolf:multiplatform-settings-serialization", version.ref = "multiplatform-settings" }
# https://github.com/Kotlin/kotlinx.serialization
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }
# https://github.com/Kotlin/kotlinx-datetime
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
# https://github.com/mikepenz/AboutLibraries
about-libraries-core = { module = "com.mikepenz:aboutlibraries-core", version.ref = "about-libraries" }
about-libraries-compose-m3 = { module = "com.mikepenz:aboutlibraries-compose-m3", version.ref = "about-libraries" }
# https://github.com/coil-kt/coil
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
# https://github.com/panpf/zoomimage
zoomimage-compose-coil3 = { module = "io.github.panpf.zoomimage:zoomimage-compose-coil3", version.ref = "zoomimage" }
# https://github.com/iBotPeaches/Apktool
apktool-lib = { module = "org.apktool:apktool-lib", version.ref = "apktool" }
# https://github.com/ktorio/ktor
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-apache5 = { module = "io.ktor:ktor-client-apache5", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
# https://github.com/MohamedRejeb/compose-rich-editor
richeditor-compose = { module = "com.mohamedrejeb.richeditor:richeditor-compose", version.ref = "richeditor" }
# https://github.com/alexzhirkevich/compottie
compottie = { module = "io.github.alexzhirkevich:compottie", version.ref = "compottie" }
compottie-dot = { module = "io.github.alexzhirkevich:compottie-dot", version.ref = "compottie" }
compottie-resources = { module = "io.github.alexzhirkevich:compottie-resources", version.ref = "compottie" }

[plugins]
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
# https://github.com/gmazzo/gradle-buildconfig-plugin
githubBuildconfig = { id = "com.github.gmazzo.buildconfig", version.ref = "buildconfig" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
about-libraries = { id = "com.mikepenz.aboutlibraries.plugin", version.ref = "about-libraries" }
# https://github.com/JetBrains/compose-hot-reload
hot-reload = { id = "org.jetbrains.compose.hot-reload", version.ref = "hot-reload" }
foojay-resolver-convention = { id = "org.gradle.toolchains.foojay-resolver-convention", version.ref = "foojay" }